### ISSUE TITLE
Restrictions not completely working 

### ISSUE THREAD

**Issue by lucyktan** [hne3/EECS-393-Nutrition-App#54]
In both search and suggestions

**Comment by 12wrigja** [comment]
Can you please elaborate on this? Food search does take into account restrictions as far as I know and suggestions might (I'm pretty sure I added this in before we demoed but I don't remember if it's committed).

**Comment by lucyktan** [comment]
I searched for nuts with a nut allergy in an account and I still got nuts.
Also got a food with nuts in the name from suggestion too. This is on the
most recent master. And I reseeded too.

**Comment by 12wrigja** [comment]
The limitations are not in any of the seeded data - they need to be made manually. I don't currently have plans to go through and add in seeding data for any of that because that will take ages - checking each food against each allergy takes far too long (8.5k ^ 5 checks to be exact). 

You can check to make sure these work by manually adding them. I'll post something shortly that can be used in tinker to add some in.

**Comment by 12wrigja** [comment]
As of Commit 5d0d10c this is fixed - if you seed the database there are basic restrictions in there for nut allergies. Anything that has the word nut in it is tagged which while I know thats not nearly good enough it's good enough to demo the concept.
